spring.application.name=microserviceproject
spring.datasource.url=jdbc:mysql://localhost:3306/CrudRestaurant?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8085
# Twilio Configuration
twilio.account-sid=ACa7d54ce62567c615f007ad83d591e6ce
twilio.auth-token=f3f8e7a015460cf56c9b60c8c7e37ae8
twilio.phone-number=+18159402630

# Recipient Phone Number
recipient.phone.number=+21621624277

