spring.application.name=microserviceproject
spring.datasource.url=jdbc:mysql://localhost:3306/CrudRestaurant?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8085
# Twilio Configuration
twilio.account-sid=
twilio.auth-token=
twilio.phone-number=

# Recipient Phone Number
recipient.phone.number=+21621624277

